### ISSUE TITLE
[1.6.0][pods] Missing required attribute `summary`

### ISSUE THREAD

**Issue by Bardiamist** [streem/react-native-select-contact#44]
Error on `pod install`:

```
[!] The `react-native-select-contact` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `summary`.
```

**Comment by seanadkinson** [comment]
Hi there.  Can you try to install `1.5.0` and see if this has the same issue?  We just pushed `1.6.0` earlier today, but the changes were minimal.

**Comment by Bardiamist** [comment]
Hmm, yes, I reverted to `1.5.0` but still have that problem on pod install. Although it was not there before.

**Comment by seanadkinson** [comment]
@Bardiamist I just pushed `v1.6.1` with a `summary` added to `package.json`, which sounds like it might fix the issue, based on some quick googling.  Give it a try?

**Comment by Bardiamist** [comment]
Update: On `1.5.0` `pod install` works (I just didn't `yarn` before `pod install` previously).

Still error on `1.6.1`.

**Comment by seanadkinson** [comment]
At what point does the error occur?  Can you provide console output?

Here is what I get in a sample project:
```
$ yarn add react-native-select-contact@1.6.1
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-dom@17.0.1" has incorrect peer dependency "react@17.0.1".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ react-native-select-contact@1.6.1
info All dependencies
└─ react-native-select-contact@1.6.1
```

**Comment by seanadkinson** [comment]
Oh, nevermind... i reproduced on `pod install`, as you mentioned.

**Comment by seanadkinson** [comment]
Alright, we needed to use `description` in the `package.json`.  Not really sure why this would've been introduce in `1.6`, but I've verified `1.6.2` has this resolved now.  I'll close, but reopen if you see anything weird.  Thanks!
